spring:
  cloud:
    gateway:
      routes:
        - id: user_services
          uri: http://localhost:8000   # URI of the user-service
          predicates:
            - Path=/api/web/v1/user/**
          filters:
            - AddRequestHeader=X-Request-User, UserGateway   # Example of adding headers
            - RewritePath=/users/(?<segment>.*), /${segment}  # Optional: Rewriting the path

        - id: contact_services
          uri: http://localhost:8001  # URI of the product-service
          predicates:
            - Path=/api/web/v1/contact/**
          filters:
            - AddRequestHeader=X-Request-Product, ProductGateway
            - RewritePath=/products/(?<segment>.*), /${segment}

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - RemoveRequestHeader=Cookie

server:
   port: 9000
